markdown: kramdown
author: "jonsvein Heinesen"

kramdown:
  math_engine: mathjax            # enable math
  math_delimiters: dollar         # accept $…$ and $$…$$ as well
  math_engine_opts:               # optional, but tidy
    preview: false

plugins:
  - jekyll-mermaid

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  config:
    startOnLoad: true
    securityLevel: loose
