# _config.yml  – this one parses
markdown: kramdown
author: "jonsvein Heinesen"

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    inline_math_delimiters:
      - ['\(', '\)']
    display_math_delimiters:
      - ['

\[', '\]

']
      - ['$$', '$$']
