# ---------------------------------------------------------------
#  _config.yml  – plain, no “$” delimiters
# ---------------------------------------------------------------

markdown: kramdown            # default engine
# no markdown_ext line → .md / .markdown only

kramdown:
  input: GFM
  math_engine: mathjax        # uses MathJax v3 on GitHub Pages

  # we omit math_engine_opts entirely → Kramdown uses:
  #   inline  : \( … \)
  #   display : 

\[ … \]

  or  $$ … $$
  # “$ … $” is ignored

  hard_wrap: false
  syntax_highlighter_opts:
    disable: true             # keeps MathJax spans untouched

author: "jonsvein Heinesen"

collections:
  ladder:
    output: true
    directory: "Ladder"
    permalink: "/ladder/:name/"
