# ---------------------------------------------------------------
#  _config.yml   ––  back-slash fixed, MathJax ready
# ---------------------------------------------------------------

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  math_engine_opts:
    inline_math_delimiters:
      - ['\(', '\)']         # ← single quotes, one back-slash each
      - ['$',  '$']
    display_math_delimiters:
      - ['

\[', '\]

']         # ← same here
      - ['$$', '$$']
  syntax_highlighter_opts:
    disable: true

author: "jonsvein Heinesen"

collections:
  ladder:
    output: true
    directory: "Ladder"
    permalink: "/ladder/:name/"
