# ---------------------------------------------------------------
#  _config.yml  – Markdown everywhere, MathJax v3 ready
# ---------------------------------------------------------------

markdown: kramdown
markdown_ext: "md,markdown,html"   # treat .html with front-matter as Markdown

kramdown:
  input: GFM
  hard_wrap: false

  math_engine: mathjax
  math_engine_opts:
    inline_math_delimiters:
      - ['\\(', '\\)']   #  \( … \)
      - ['$',  '$']      #  $ … $
    display_math_delimiters:
      - ['\

\[', '\\]

']   #  

\[ … \]


      - ['$$', '$$']     #  $$ … $$

  syntax_highlighter_opts:
    disable: true        # you don’t need Rouge if you rely on plain <pre>

author: "jonsvein Heinesen"

collections:
  ladder:
    output: true
    directory: "Ladder"
    permalink: "/ladder/:name/"

