# ---------------------------------------------------------------------
#  _config.yml  —  MathJax-ready settings
# ---------------------------------------------------------------------

markdown: kramdown      # (default, but state it explicitly)

kramdown:
  input: GFM
  hard_wrap: false      # critical: true inserts <br> that break fractions
  math_engine: mathjax
  math_engine_opts:
    # Inline math  →  \( … \)   or   $…$
    inline_math_delimiters: [['\\(', '\\)'], ['$', '$']]
    # Display math →  

\[ … \]

   or   $$ … $$
    display_math_delimiters: [['\

\[', '\\]

'], ['$$', '$$']]
  syntax_highlighter_opts:
    disable: true       # prevent Rouge from mangling TeX backslashes

# --- Site metadata ---------------------------------------------------
author: "jonsvein Heinesen"

# --- Collections -----------------------------------------------------
collections:
  ladder:
    output: true
    directory: Ladder          # physical folder (case-sensitive)
    permalink: /ladder/:name/  # final URL: /ladder/filename/

