# ---------------------------------------------------------------
#  _config.yml  –– MathJax-ready and YAML-lint clean
# ---------------------------------------------------------------

# 1 Markdown engine
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false           # true inserts <br>; false keeps math intact
  math_engine: mathjax
  math_engine_opts:
    # inline math pairs
    inline_math_delimiters:
      - ["\\(", "\\)"]
      - ["$", "$"]
    # display math pairs
    display_math_delimiters:
      - ["\

\[", "\\]

"]
      - ["$$", "$$"]
  syntax_highlighter_opts:
    disable: true            # avoid Rouge clobbering TeX backslashes

# 2 Site metadata
author: "jonsvein Heinesen"

# 3 Collections
collections:
  ladder:
    output: true
    directory: "Ladder"      # physical folder (case-sensitive)
    permalink: "/ladder/:name/"
