# _config.yml  – compact & YAML-valid
markdown: kramdown
author: "jonsvein Heinesen"

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    inline_math_delimiters:
      - ['\\(', '\\)']          # \( … \)
    display_math_delimiters:
      - ['\

\[', '\\]

']          # 

\[ … \]


      - ['$$',  '$$']           # $$ … $$
  syntax_highlighter_opts:
    disable: true               # keep MathJax spans intact

collections:
  ladder:
    output: true
    directory: "Ladder"
    permalink: "/ladder/:name/"

