# _config.yml  – verified on Ruby 3.3 / Psych 5.1
markdown: kramdown
author: "jonsvein Heinesen"

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    inline_math_delimiters:
      - - "\\("
        - "\\)"
    display_math_delimiters:
      - - "\



