markdown: kramdown
author: "jonsvein Heinesen"

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false


plugins:
  - jekyll-mermaid

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  config:
    startOnLoad: true
    securityLevel: loose
